/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exemplo */

#ifndef _Included_Exemplo
#define _Included_Exemplo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exemplo
 * Method:    start
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Exemplo_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
